DROP TABLE IF EXISTS pins CASCADE;
CREATE TABLE pins (
  id SERIAL PRIMARY KEY NOT NULL,
  creator_id INTEGER NOT NULL REFERENCES users(id),
  map_id INTEGER NOT NULL REFERENCES maps(id),
  latitude DECIMAL NOT NULL,
  longitude DECIMAL NOT NULL,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  image_url TEXT
);
